name = "trip-khaoyai"
compatibility_date = "2026-09-01"
account_id = "a24ce30584273b42333051f1cdec48e2"
routes = [{ pattern = "trip.jairukchan.com", custom_domain = true }]
workers_dev = true

[assets]
directory = "./public"
not_found_handling = "single-page-application"
